[package]
name = "photo-sorter-core"
version = "0.1.0"
edition = "2024"
description = "Rust photo sorter GUI"
authors.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
photo-sorter-core = { path = "../core" }
eframe = { workspace = true }
rfd = { workspace = true }
anyhow = { workspace = true }
