[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
# 文件遍历
walkdir = "2"

# EXIF 读取
kamadak-exif = "0.5"

# 日期时间 读取
chrono = "0.4"

# 自定义错误
thiserror = "1"

# 命令行解析
clap = { version = "4", features = ["derive"] }

# 错误处理
anyhow = "1"

# GUI
eframe = "0.27"

# 文件对话框
rfd = "0.14"
