[package]
name = "photo-sorter-cli"
version = "0.1.0"
edition = "2024"
description = "Rust photo sorter CLI"
authors.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
photo-sorter-core = { path = "../core" }
clap = { workspace = true }
anyhow = { workspace = true }
